import type { Task } from './types'

export const mockTasks: Task[] = [
  {
    id: 'task-001',
    title: 'Implement passwordless sign-in',
    description: 'Add magic-link authentication for invited workspace members and track delivery failures.',
    priority: 'high',
    dueDate: '2026-06-12',
    assignee: 'Ava Mitchell',
    status: 'todo',
    tags: ['auth', 'backend', 'blocked'],
    createdAt: '2026-05-28T09:15:00.000Z',
  },
  {
    id: 'task-002',
    title: 'Refine dashboard empty states',
    description: 'Design clearer first-run states for projects, task groups, and archived lists.',
    priority: 'medium',
    dueDate: '2026-06-24',
    assignee: 'Noah Patel',
    status: 'in-progress',
    tags: ['ux', 'design-system'],
    createdAt: '2026-05-30T13:40:00.000Z',
  },
  {
    id: 'task-003',
    title: 'Add audit log export',
    description: 'Let admins download filtered workspace activity as CSV for compliance reviews.',
    priority: 'high',
    dueDate: '2026-06-17',
    assignee: 'Mia Rodriguez',
    status: 'in-progress',
    tags: ['backend', 'compliance'],
    createdAt: '2026-06-01T10:05:00.000Z',
  },
  {
    id: 'task-004',
    title: 'Fix recurring task timezone drift',
    description: 'Recurring reminders should preserve local wall-clock time across daylight saving changes.',
    priority: 'high',
    dueDate: '2026-06-10',
    assignee: 'Ethan Chen',
    status: 'todo',
    tags: ['bug', 'calendar'],
    createdAt: '2026-06-02T16:20:00.000Z',
  },
  {
    id: 'task-005',
    title: 'Ship notification preferences panel',
    description: 'Expose email, push, and digest controls with per-project overrides.',
    priority: 'medium',
    dueDate: '2026-06-28',
    assignee: 'Ava Mitchell',
    status: 'todo',
    tags: ['settings', 'frontend'],
    createdAt: '2026-06-04T08:45:00.000Z',
  },
  {
    id: 'task-006',
    title: 'Optimize board query performance',
    description: 'Reduce payload size and add pagination support for workspaces with thousands of tasks.',
    priority: 'high',
    dueDate: '2026-07-02',
    assignee: "Liam O'Connor",
    status: 'in-progress',
    tags: ['performance', 'backend'],
    createdAt: '2026-06-05T11:25:00.000Z',
  },
  {
    id: 'task-007',
    title: 'Document webhook retry behavior',
    description: 'Clarify retry timing, failure headers, and signature validation in developer docs.',
    priority: 'low',
    dueDate: '2026-06-30',
    assignee: 'Mia Rodriguez',
    status: 'done',
    tags: ['docs', 'api'],
    createdAt: '2026-06-06T15:10:00.000Z',
  },
  {
    id: 'task-008',
    title: 'Improve task search relevance',
    description: 'Weight exact title matches above stale description matches and include tag synonyms.',
    priority: 'medium',
    dueDate: '2026-07-05',
    assignee: 'Noah Patel',
    status: 'todo',
    tags: ['search', 'frontend'],
    createdAt: '2026-06-07T12:30:00.000Z',
  },
  {
    id: 'task-009',
    title: 'Add billing usage warnings',
    description: 'Notify workspace owners before automation runs exceed their included monthly quota.',
    priority: 'medium',
    dueDate: '2026-06-15',
    assignee: 'Ethan Chen',
    status: 'in-progress',
    tags: ['billing', 'notifications'],
    createdAt: '2026-06-08T09:50:00.000Z',
  },
  {
    id: 'task-010',
    title: 'Clean up legacy project colors',
    description: 'Migrate unsupported palette values and add fallbacks for imported projects.',
    priority: 'low',
    dueDate: '2026-06-21',
    assignee: 'Ava Mitchell',
    status: 'done',
    tags: ['migration'],
    createdAt: '2026-06-09T14:35:00.000Z',
  },
  {
    id: 'task-011',
    title: 'Create onboarding checklist metrics',
    description: 'Track completion rates for workspace setup steps and expose drop-off reporting.',
    priority: 'low',
    dueDate: '2026-07-08',
    assignee: "Liam O'Connor",
    status: 'done',
    tags: ['analytics', 'onboarding'],
    createdAt: '2026-06-11T10:00:00.000Z',
  },
  {
    id: 'task-012',
    title: 'Prototype bulk task actions',
    description: 'Explore multi-select flows for assigning, moving, and archiving tasks from the list view.',
    priority: 'low',
    dueDate: '2026-07-10',
    assignee: 'Noah Patel',
    status: 'todo',
    tags: ['ux', 'list-view'],
    createdAt: '2026-06-12T17:05:00.000Z',
  },
]
